# Generated by Django 5.2.9 on 2025-12-18 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VKGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.IntegerField(unique=True, verbose_name='ID группы')),
                ('name', models.CharField(max_length=255, verbose_name='Название группы')),
                ('access_token', models.CharField(max_length=255, verbose_name='Токен доступа')),
                ('secret_key', models.CharField(blank=True, max_length=50, verbose_name='Секретный ключ')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
        ),
        migrations.CreateModel(
            name='VKMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.IntegerField(verbose_name='ID сообщения ВК')),
                ('from_id', models.IntegerField(verbose_name='ID отправителя')),
                ('from_name', models.CharField(max_length=255, verbose_name='Имя отправителя')),
                ('text', models.TextField(verbose_name='Текст сообщения')),
                ('attachments', models.JSONField(blank=True, default=list, verbose_name='Вложения')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата получения')),
                ('status', models.CharField(choices=[('new', 'Новое'), ('in_progress', 'В обработке'), ('answered', 'Отвечено'), ('closed', 'Закрыто')], default='new', max_length=20)),
                ('response', models.TextField(blank=True, verbose_name='Ответ администратора')),
                ('response_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата ответа')),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
                ('vk_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicedesk.vkgroup', verbose_name='Группа ВК')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
