# Generated by Django 5.2.9 on 2025-12-18 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VKUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vk_id', models.BigIntegerField(unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'VK Пользователь',
                'verbose_name_plural': 'VK Пользователи',
            },
        ),
        migrations.CreateModel(
            name='VKMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('vk_message_id', models.BigIntegerField()),
                ('direction', models.CharField(choices=[('incoming', 'Входящее'), ('outgoing', 'Исходящее')], max_length=10)),
                ('timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='servicedesk.vkuser')),
            ],
            options={
                'verbose_name': 'VK Сообщение',
                'verbose_name_plural': 'VK Сообщения',
                'indexes': [models.Index(fields=['vk_message_id'], name='servicedesk_vk_mess_066522_idx'), models.Index(fields=['timestamp'], name='servicedesk_timesta_e6503b_idx')],
            },
        ),
    ]
