# Generated by Django 5.2.9 on 2025-12-23 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicedesk', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название тега')),
                ('color', models.CharField(default='#6c757d', max_length=7, verbose_name='Цвет (HEX)')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(max_length=20, unique=True, verbose_name='Номер обращения')),
                ('user_id', models.IntegerField(verbose_name='ID пользователя ВК')),
                ('user_name', models.CharField(max_length=255, verbose_name='Имя пользователя')),
                ('user_photo', models.URLField(blank=True, verbose_name='Фото пользователя')),
                ('subject', models.CharField(default='Без темы', max_length=255, verbose_name='Тема обращения')),
                ('status', models.CharField(choices=[('open', 'Открыто'), ('answered', 'Отвечено'), ('waiting', 'Ожидание'), ('closed', 'Закрыто')], default='open', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий'), ('critical', 'Критический')], default='medium', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Закрыто')),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
                ('tags', models.ManyToManyField(blank=True, to='servicedesk.tag', verbose_name='Теги')),
                ('vk_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicedesk.vkgroup', verbose_name='Группа ВК')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.IntegerField(blank=True, null=True, verbose_name='ID сообщения ВК')),
                ('text', models.TextField(verbose_name='Текст сообщения')),
                ('attachments', models.JSONField(blank=True, default=list, verbose_name='Вложения')),
                ('is_admin', models.BooleanField(default=False, verbose_name='От администратора')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('admin_author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор (админ)')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='servicedesk.ticket', verbose_name='Обращение')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.DeleteModel(
            name='VKMessage',
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status', 'priority'], name='servicedesk_status_6a194f_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['user_id', 'created_at'], name='servicedesk_user_id_797886_idx'),
        ),
    ]
