# Generated by Django 5.2.9 on 2025-12-23 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicedesk', '0002_tag_ticket_message_delete_vkmessage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='user_photo',
            field=models.URLField(blank=True, max_length=2048, verbose_name='Фото пользователя'),
        ),
    ]
